<?php declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/Tracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Trace.QueryPlanNode.DeferredNode</code>.
 */
class DeferredNode extends \Google\Protobuf\Internal\Message
{
    /** Generated from protobuf field <code>repeated .Trace.QueryPlanNode.DeferredNodeDepends depends = 1;</code> */
    private $depends;

    /** Generated from protobuf field <code>string label = 2;</code> */
    protected $label = '';

    /** Generated from protobuf field <code>repeated .Trace.QueryPlanNode.ResponsePathElement path = 3;</code> */
    private $path;

    /** Generated from protobuf field <code>.Trace.QueryPlanNode node = 4;</code> */
    protected $node;

    /**
     * Constructor.
     *
     * @param  array  $data {
     *     Optional. Data for populating the Message object.
     *
     *     @var array<\Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode\DeferredNodeDepends>|\Google\Protobuf\Internal\RepeatedField $depends
     *     @var string $label
     *     @var array<\Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode\ResponsePathElement>|\Google\Protobuf\Internal\RepeatedField $path
     *     @var \Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode $node
     * }
     */
    public function __construct($data = null)
    {
        \Nuwave\Lighthouse\Tracing\Proto\Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Trace.QueryPlanNode.DeferredNodeDepends depends = 1;</code>.
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDepends()
    {
        return $this->depends;
    }

    /**
     * Generated from protobuf field <code>repeated .Trace.QueryPlanNode.DeferredNodeDepends depends = 1;</code>.
     *
     * @param  array<\Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode\DeferredNodeDepends>|\Google\Protobuf\Internal\RepeatedField  $var
     *
     * @return $this
     */
    public function setDepends(array|\Google\Protobuf\Internal\RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode\DeferredNodeDepends::class);
        $this->depends = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string label = 2;</code>.
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>string label = 2;</code>.
     *
     * @param  string  $var
     *
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, true);
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Trace.QueryPlanNode.ResponsePathElement path = 3;</code>.
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>repeated .Trace.QueryPlanNode.ResponsePathElement path = 3;</code>.
     *
     * @param  array<\Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode\ResponsePathElement>|\Google\Protobuf\Internal\RepeatedField  $var
     *
     * @return $this
     */
    public function setPath(array|\Google\Protobuf\Internal\RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode\ResponsePathElement::class);
        $this->path = $arr;

        return $this;
    }

    /** Generated from protobuf field <code>.Trace.QueryPlanNode node = 4;</code> */
    public function getNode(): ?\Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode
    {
        return $this->node;
    }

    public function hasNode()
    {
        return isset($this->node);
    }

    public function clearNode(): void
    {
        unset($this->node);
    }

    /**
     * Generated from protobuf field <code>.Trace.QueryPlanNode node = 4;</code>.
     *
     * @param  \Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode  $var
     *
     * @return $this
     */
    public function setNode($var)
    {
        GPBUtil::checkMessage($var, \Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode::class);
        $this->node = $var;

        return $this;
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DeferredNode::class, \Nuwave\Lighthouse\Tracing\Proto\Trace_QueryPlanNode_DeferredNode::class);
