<?php declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/Tracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode;

use Google\Protobuf\Internal\GPBUtil;

/**
 * This represents a node to send an operation to an implementing service.
 *
 * Generated from protobuf message <code>Trace.QueryPlanNode.FetchNode</code>
 */
class FetchNode extends \Google\Protobuf\Internal\Message
{
    /**
     * XXX When we want to include more details about the sub-operation that was
     * executed against this service, we should include that here in each fetch node.
     * This might include an operation signature, requires directive, reference resolutions, etc.
     *
     * Generated from protobuf field <code>string service_name = 1;</code>
     */
    protected $service_name = '';

    /** Generated from protobuf field <code>bool trace_parsing_failed = 2;</code> */
    protected $trace_parsing_failed = false;

    /**
     * This Trace only contains start_time, end_time, duration_ns, and root;
     * all timings were calculated **on the subgraph**, and clock skew
     * will be handled by the ingress server.
     *
     * Generated from protobuf field <code>.Trace trace = 3;</code>
     */
    protected ?\Nuwave\Lighthouse\Tracing\Proto\Trace $trace = null;

    /**
     * relative to the outer trace's start_time, in ns, measured in the Router/Gateway.
     *
     * Generated from protobuf field <code>uint64 sent_time_offset = 4;</code>
     */
    protected $sent_time_offset = 0;

    /**
     * Wallclock times measured in the Router/Gateway for when this operation was
     * sent and received.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp sent_time = 5;</code>
     */
    protected ?\Google\Protobuf\Timestamp $sent_time = null;

    /** Generated from protobuf field <code>.google.protobuf.Timestamp received_time = 6;</code> */
    protected ?\Google\Protobuf\Timestamp $received_time = null;

    /**
     * Constructor.
     *
     * @param  array  $data {
     *     Optional. Data for populating the Message object.
     *
     *     @var string $service_name
     *           XXX When we want to include more details about the sub-operation that was
     *           executed against this service, we should include that here in each fetch node.
     *           This might include an operation signature, requires directive, reference resolutions, etc.
     *     @var bool $trace_parsing_failed
     *     @var \Nuwave\Lighthouse\Tracing\Proto\Trace $trace
     *           This Trace only contains start_time, end_time, duration_ns, and root;
     *           all timings were calculated **on the subgraph**, and clock skew
     *           will be handled by the ingress server
     *     @var int|string $sent_time_offset
     *           relative to the outer trace's start_time, in ns, measured in the Router/Gateway
     *     @var \Google\Protobuf\Timestamp $sent_time
     *           Wallclock times measured in the Router/Gateway for when this operation was
     *           sent and received
     *     @var \Google\Protobuf\Timestamp $received_time
     * }
     */
    public function __construct($data = null)
    {
        \Nuwave\Lighthouse\Tracing\Proto\Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /**
     * XXX When we want to include more details about the sub-operation that was
     * executed against this service, we should include that here in each fetch node.
     * This might include an operation signature, requires directive, reference resolutions, etc.
     *
     * Generated from protobuf field <code>string service_name = 1;</code>
     *
     * @return string
     */
    public function getServiceName()
    {
        return $this->service_name;
    }

    /**
     * XXX When we want to include more details about the sub-operation that was
     * executed against this service, we should include that here in each fetch node.
     * This might include an operation signature, requires directive, reference resolutions, etc.
     *
     * Generated from protobuf field <code>string service_name = 1;</code>
     *
     * @param  string  $var
     *
     * @return $this
     */
    public function setServiceName($var)
    {
        GPBUtil::checkString($var, true);
        $this->service_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool trace_parsing_failed = 2;</code>.
     *
     * @return bool
     */
    public function getTraceParsingFailed()
    {
        return $this->trace_parsing_failed;
    }

    /**
     * Generated from protobuf field <code>bool trace_parsing_failed = 2;</code>.
     *
     * @param  bool  $var
     *
     * @return $this
     */
    public function setTraceParsingFailed($var)
    {
        GPBUtil::checkBool($var);
        $this->trace_parsing_failed = $var;

        return $this;
    }

    /**
     * This Trace only contains start_time, end_time, duration_ns, and root;
     * all timings were calculated **on the subgraph**, and clock skew
     * will be handled by the ingress server.
     *
     * Generated from protobuf field <code>.Trace trace = 3;</code>
     */
    public function getTrace(): ?\Nuwave\Lighthouse\Tracing\Proto\Trace
    {
        return $this->trace;
    }

    public function hasTrace()
    {
        return isset($this->trace);
    }

    public function clearTrace(): void
    {
        unset($this->trace);
    }

    /**
     * This Trace only contains start_time, end_time, duration_ns, and root;
     * all timings were calculated **on the subgraph**, and clock skew
     * will be handled by the ingress server.
     *
     * Generated from protobuf field <code>.Trace trace = 3;</code>
     *
     * @return $this
     */
    public function setTrace(?\Nuwave\Lighthouse\Tracing\Proto\Trace $var)
    {
        GPBUtil::checkMessage($var, \Nuwave\Lighthouse\Tracing\Proto\Trace::class);
        $this->trace = $var;

        return $this;
    }

    /**
     * relative to the outer trace's start_time, in ns, measured in the Router/Gateway.
     *
     * Generated from protobuf field <code>uint64 sent_time_offset = 4;</code>
     */
    public function getSentTimeOffset(): int|string
    {
        return $this->sent_time_offset;
    }

    /**
     * relative to the outer trace's start_time, in ns, measured in the Router/Gateway.
     *
     * Generated from protobuf field <code>uint64 sent_time_offset = 4;</code>
     *
     * @return $this
     */
    public function setSentTimeOffset(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->sent_time_offset = $var;

        return $this;
    }

    /**
     * Wallclock times measured in the Router/Gateway for when this operation was
     * sent and received.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp sent_time = 5;</code>
     */
    public function getSentTime(): ?\Google\Protobuf\Timestamp
    {
        return $this->sent_time;
    }

    public function hasSentTime()
    {
        return isset($this->sent_time);
    }

    public function clearSentTime(): void
    {
        unset($this->sent_time);
    }

    /**
     * Wallclock times measured in the Router/Gateway for when this operation was
     * sent and received.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp sent_time = 5;</code>
     *
     * @return $this
     */
    public function setSentTime(?\Google\Protobuf\Timestamp $var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->sent_time = $var;

        return $this;
    }

    /** Generated from protobuf field <code>.google.protobuf.Timestamp received_time = 6;</code> */
    public function getReceivedTime(): ?\Google\Protobuf\Timestamp
    {
        return $this->received_time;
    }

    public function hasReceivedTime()
    {
        return isset($this->received_time);
    }

    public function clearReceivedTime(): void
    {
        unset($this->received_time);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp received_time = 6;</code>.
     *
     * @return $this
     */
    public function setReceivedTime(?\Google\Protobuf\Timestamp $var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->received_time = $var;

        return $this;
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(FetchNode::class, \Nuwave\Lighthouse\Tracing\Proto\Trace_QueryPlanNode_FetchNode::class);
