<?php declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/Tracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode;

use Google\Protobuf\Internal\GPBUtil;

/**
 * This node represents a way to reach into the response path and attach related entities.
 * XXX Flatten is really not the right name and this node may be renamed in the query planner.
 *
 * Generated from protobuf message <code>Trace.QueryPlanNode.FlattenNode</code>
 */
class FlattenNode extends \Google\Protobuf\Internal\Message
{
    /** Generated from protobuf field <code>repeated .Trace.QueryPlanNode.ResponsePathElement response_path = 1;</code> */
    private $response_path;

    /** Generated from protobuf field <code>.Trace.QueryPlanNode node = 2;</code> */
    protected ?\Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode $node = null;

    /**
     * Constructor.
     *
     * @param  array  $data {
     *     Optional. Data for populating the Message object.
     *
     *     @var array<\Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode\ResponsePathElement>|\Google\Protobuf\Internal\RepeatedField $response_path
     *     @var \Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode $node
     * }
     */
    public function __construct($data = null)
    {
        \Nuwave\Lighthouse\Tracing\Proto\Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Trace.QueryPlanNode.ResponsePathElement response_path = 1;</code>.
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResponsePath()
    {
        return $this->response_path;
    }

    /**
     * Generated from protobuf field <code>repeated .Trace.QueryPlanNode.ResponsePathElement response_path = 1;</code>.
     *
     * @param  array<\Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode\ResponsePathElement>|\Google\Protobuf\Internal\RepeatedField  $var
     *
     * @return $this
     */
    public function setResponsePath(array|\Google\Protobuf\Internal\RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode\ResponsePathElement::class);
        $this->response_path = $arr;

        return $this;
    }

    /** Generated from protobuf field <code>.Trace.QueryPlanNode node = 2;</code> */
    public function getNode(): ?\Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode
    {
        return $this->node;
    }

    public function hasNode()
    {
        return isset($this->node);
    }

    public function clearNode(): void
    {
        unset($this->node);
    }

    /**
     * Generated from protobuf field <code>.Trace.QueryPlanNode node = 2;</code>.
     *
     * @return $this
     */
    public function setNode(?\Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode $var)
    {
        GPBUtil::checkMessage($var, \Nuwave\Lighthouse\Tracing\Proto\Trace\QueryPlanNode::class);
        $this->node = $var;

        return $this;
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(FlattenNode::class, \Nuwave\Lighthouse\Tracing\Proto\Trace_QueryPlanNode_FlattenNode::class);
