<?php declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/Tracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\Proto;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ContextualizedQueryLatencyStats</code>.
 */
class ContextualizedQueryLatencyStats extends \Google\Protobuf\Internal\Message
{
    /** Generated from protobuf field <code>.QueryLatencyStats query_latency_stats = 1;</code> */
    protected $query_latency_stats;

    /** Generated from protobuf field <code>.StatsContext context = 2;</code> */
    protected $context;

    /**
     * Constructor.
     *
     * @param  array  $data {
     *     Optional. Data for populating the Message object.
     *
     *     @var \Nuwave\Lighthouse\Tracing\Proto\QueryLatencyStats $query_latency_stats
     *     @var \Nuwave\Lighthouse\Tracing\Proto\StatsContext $context
     * }
     */
    public function __construct($data = null)
    {
        \Nuwave\Lighthouse\Tracing\Proto\Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /** Generated from protobuf field <code>.QueryLatencyStats query_latency_stats = 1;</code> */
    public function getQueryLatencyStats(): ?QueryLatencyStats
    {
        return $this->query_latency_stats;
    }

    public function hasQueryLatencyStats()
    {
        return isset($this->query_latency_stats);
    }

    public function clearQueryLatencyStats(): void
    {
        unset($this->query_latency_stats);
    }

    /**
     * Generated from protobuf field <code>.QueryLatencyStats query_latency_stats = 1;</code>.
     *
     * @param  \Nuwave\Lighthouse\Tracing\Proto\QueryLatencyStats  $var
     *
     * @return $this
     */
    public function setQueryLatencyStats($var)
    {
        GPBUtil::checkMessage($var, \Nuwave\Lighthouse\Tracing\Proto\QueryLatencyStats::class);
        $this->query_latency_stats = $var;

        return $this;
    }

    /** Generated from protobuf field <code>.StatsContext context = 2;</code> */
    public function getContext(): ?StatsContext
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext(): void
    {
        unset($this->context);
    }

    /**
     * Generated from protobuf field <code>.StatsContext context = 2;</code>.
     *
     * @param  \Nuwave\Lighthouse\Tracing\Proto\StatsContext  $var
     *
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \Nuwave\Lighthouse\Tracing\Proto\StatsContext::class);
        $this->context = $var;

        return $this;
    }
}
