<?php declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/Tracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\Proto;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ContextualizedTypeStats</code>.
 */
class ContextualizedTypeStats extends \Google\Protobuf\Internal\Message
{
    /** Generated from protobuf field <code>.StatsContext context = 1;</code> */
    protected ?\Nuwave\Lighthouse\Tracing\Proto\StatsContext $context = null;

    /** Generated from protobuf field <code>map<string, .TypeStat> per_type_stat = 2;</code> */
    private $per_type_stat;

    /**
     * Constructor.
     *
     * @param  array  $data {
     *     Optional. Data for populating the Message object.
     *
     *     @var \Nuwave\Lighthouse\Tracing\Proto\StatsContext $context
     *     @var array|\Google\Protobuf\Internal\MapField $per_type_stat
     * }
     */
    public function __construct($data = null)
    {
        \Nuwave\Lighthouse\Tracing\Proto\Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /** Generated from protobuf field <code>.StatsContext context = 1;</code> */
    public function getContext(): ?StatsContext
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext(): void
    {
        unset($this->context);
    }

    /**
     * Generated from protobuf field <code>.StatsContext context = 1;</code>.
     *
     * @param  \Nuwave\Lighthouse\Tracing\Proto\StatsContext  $var
     *
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \Nuwave\Lighthouse\Tracing\Proto\StatsContext::class);
        $this->context = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .TypeStat> per_type_stat = 2;</code>.
     *
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPerTypeStat()
    {
        return $this->per_type_stat;
    }

    /**
     * Generated from protobuf field <code>map<string, .TypeStat> per_type_stat = 2;</code>.
     *
     * @return $this
     */
    public function setPerTypeStat(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nuwave\Lighthouse\Tracing\Proto\TypeStat::class);
        $this->per_type_stat = $arr;

        return $this;
    }
}
