<?php declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/Tracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\Proto\Trace;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Trace.CachePolicy</code>.
 */
class CachePolicy extends \Google\Protobuf\Internal\Message
{
    /** Generated from protobuf field <code>.Trace.CachePolicy.Scope scope = 1;</code> */
    protected $scope = 0;

    /**
     * use 0 for absent, -1 for 0.
     *
     * Generated from protobuf field <code>int64 max_age_ns = 2;</code>
     */
    protected $max_age_ns = 0;

    /**
     * Constructor.
     *
     * @param  array  $data {
     *     Optional. Data for populating the Message object.
     *
     *     @var int $scope
     *     @var int|string $max_age_ns
     *           use 0 for absent, -1 for 0
     * }
     */
    public function __construct($data = null)
    {
        \Nuwave\Lighthouse\Tracing\Proto\Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Trace.CachePolicy.Scope scope = 1;</code>.
     *
     * @return int
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * Generated from protobuf field <code>.Trace.CachePolicy.Scope scope = 1;</code>.
     *
     * @param  int  $var
     *
     * @return $this
     */
    public function setScope($var)
    {
        GPBUtil::checkEnum($var);
        $this->scope = $var;

        return $this;
    }

    /**
     * use 0 for absent, -1 for 0.
     *
     * Generated from protobuf field <code>int64 max_age_ns = 2;</code>
     */
    public function getMaxAgeNs(): int|string
    {
        return $this->max_age_ns;
    }

    /**
     * use 0 for absent, -1 for 0.
     *
     * Generated from protobuf field <code>int64 max_age_ns = 2;</code>
     *
     * @return $this
     */
    public function setMaxAgeNs(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->max_age_ns = $var;

        return $this;
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CachePolicy::class, \Nuwave\Lighthouse\Tracing\Proto\Trace_CachePolicy::class);
