<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/Tracing/FederatedTracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\FederatedTracing\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ContextualizedQueryLatencyStats</code>
 */
class ContextualizedQueryLatencyStats extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.QueryLatencyStats query_latency_stats = 1 [json_name = "queryLatencyStats"];</code>
     */
    protected $query_latency_stats = null;
    /**
     * Generated from protobuf field <code>.StatsContext context = 2 [json_name = "context"];</code>
     */
    protected $context = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\QueryLatencyStats $query_latency_stats
     *     @type \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\StatsContext $context
     * }
     */
    public function __construct($data = NULL) {
        \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.QueryLatencyStats query_latency_stats = 1 [json_name = "queryLatencyStats"];</code>
     * @return \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\QueryLatencyStats|null
     */
    public function getQueryLatencyStats()
    {
        return $this->query_latency_stats;
    }

    public function hasQueryLatencyStats()
    {
        return isset($this->query_latency_stats);
    }

    public function clearQueryLatencyStats()
    {
        unset($this->query_latency_stats);
    }

    /**
     * Generated from protobuf field <code>.QueryLatencyStats query_latency_stats = 1 [json_name = "queryLatencyStats"];</code>
     * @param \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\QueryLatencyStats $var
     * @return $this
     */
    public function setQueryLatencyStats($var)
    {
        GPBUtil::checkMessage($var, \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\QueryLatencyStats::class);
        $this->query_latency_stats = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.StatsContext context = 2 [json_name = "context"];</code>
     * @return \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\StatsContext|null
     */
    public function getContext()
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext()
    {
        unset($this->context);
    }

    /**
     * Generated from protobuf field <code>.StatsContext context = 2 [json_name = "context"];</code>
     * @param \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\StatsContext $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\StatsContext::class);
        $this->context = $var;

        return $this;
    }

}

