<?php declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/Tracing/FederatedTracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\FederatedTracing\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EnumStats</code>.
 */
class EnumStats extends \Google\Protobuf\Internal\Message
{
    /**
     * Map of enum value name to the number of referencing operations.
     *
     * Generated from protobuf field <code>map<string, uint64> enum_values = 1 [json_name = "enumValues"];</code>
     */
    private $enum_values;

    /**
     * Constructor.
     *
     * @param  array  $data {
     *     Optional. Data for populating the Message object.
     *
     *     @var array|\Google\Protobuf\Internal\MapField $enum_values
     *           Map of enum value name to the number of referencing operations.
     * }
     */
    public function __construct($data = null)
    {
        Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /**
     * Map of enum value name to the number of referencing operations.
     *
     * Generated from protobuf field <code>map<string, uint64> enum_values = 1 [json_name = "enumValues"];</code>
     *
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getEnumValues()
    {
        return $this->enum_values;
    }

    /**
     * Map of enum value name to the number of referencing operations.
     *
     * Generated from protobuf field <code>map<string, uint64> enum_values = 1 [json_name = "enumValues"];</code>
     *
     * @param  array|\Google\Protobuf\Internal\MapField  $var
     *
     * @return $this
     */
    public function setEnumValues($var)
    {
        $arr = GPBUtil::checkMapField($var, GPBType::STRING, GPBType::UINT64);
        $this->enum_values = $arr;

        return $this;
    }
}
