<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/Tracing/FederatedTracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\FederatedTracing\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ExtendedReferences</code>
 */
class ExtendedReferences extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .InputTypeStats> input_types = 1 [json_name = "inputTypes"];</code>
     */
    private $input_types;
    /**
     * Map of enum name to stats about that enum.
     *
     * Generated from protobuf field <code>map<string, .EnumStats> enum_values = 2 [json_name = "enumValues"];</code>
     */
    private $enum_values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $input_types
     *     @type array|\Google\Protobuf\Internal\MapField $enum_values
     *           Map of enum name to stats about that enum.
     * }
     */
    public function __construct($data = NULL) {
        \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .InputTypeStats> input_types = 1 [json_name = "inputTypes"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getInputTypes()
    {
        return $this->input_types;
    }

    /**
     * Generated from protobuf field <code>map<string, .InputTypeStats> input_types = 1 [json_name = "inputTypes"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setInputTypes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\InputTypeStats::class);
        $this->input_types = $arr;

        return $this;
    }

    /**
     * Map of enum name to stats about that enum.
     *
     * Generated from protobuf field <code>map<string, .EnumStats> enum_values = 2 [json_name = "enumValues"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getEnumValues()
    {
        return $this->enum_values;
    }

    /**
     * Map of enum name to stats about that enum.
     *
     * Generated from protobuf field <code>map<string, .EnumStats> enum_values = 2 [json_name = "enumValues"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setEnumValues($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\EnumStats::class);
        $this->enum_values = $arr;

        return $this;
    }

}

