<?php declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/Tracing/FederatedTracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\FederatedTracing\Proto;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>InputFieldStats</code>.
 */
class InputFieldStats extends \Google\Protobuf\Internal\Message
{
    /**
     * The total number of operations that reference the input object field.
     *
     * Generated from protobuf field <code>uint64 refs = 1 [json_name = "refs"];</code>
     */
    protected $refs = 0;

    /**
     * The number of operations that reference the input object field as a null value.
     *
     * Generated from protobuf field <code>uint64 null_refs = 2 [json_name = "nullRefs"];</code>
     */
    protected $null_refs = 0;

    /**
     * The number of operations that don't reference this input object field (the field is missing or undefined).
     *
     * Generated from protobuf field <code>uint64 missing = 3 [json_name = "missing"];</code>
     */
    protected $missing = 0;

    /**
     * Constructor.
     *
     * @param  array  $data {
     *     Optional. Data for populating the Message object.
     *
     *     @var int|string $refs
     *           The total number of operations that reference the input object field.
     *     @var int|string $null_refs
     *           The number of operations that reference the input object field as a null value.
     *     @var int|string $missing
     *           The number of operations that don't reference this input object field (the field is missing or undefined).
     * }
     */
    public function __construct($data = null)
    {
        Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /**
     * The total number of operations that reference the input object field.
     *
     * Generated from protobuf field <code>uint64 refs = 1 [json_name = "refs"];</code>
     *
     * @return int|string
     */
    public function getRefs()
    {
        return $this->refs;
    }

    /**
     * The total number of operations that reference the input object field.
     *
     * Generated from protobuf field <code>uint64 refs = 1 [json_name = "refs"];</code>
     *
     * @param  int|string  $var
     *
     * @return $this
     */
    public function setRefs($var)
    {
        GPBUtil::checkUint64($var);
        $this->refs = $var;

        return $this;
    }

    /**
     * The number of operations that reference the input object field as a null value.
     *
     * Generated from protobuf field <code>uint64 null_refs = 2 [json_name = "nullRefs"];</code>
     *
     * @return int|string
     */
    public function getNullRefs()
    {
        return $this->null_refs;
    }

    /**
     * The number of operations that reference the input object field as a null value.
     *
     * Generated from protobuf field <code>uint64 null_refs = 2 [json_name = "nullRefs"];</code>
     *
     * @param  int|string  $var
     *
     * @return $this
     */
    public function setNullRefs($var)
    {
        GPBUtil::checkUint64($var);
        $this->null_refs = $var;

        return $this;
    }

    /**
     * The number of operations that don't reference this input object field (the field is missing or undefined).
     *
     * Generated from protobuf field <code>uint64 missing = 3 [json_name = "missing"];</code>
     *
     * @return int|string
     */
    public function getMissing()
    {
        return $this->missing;
    }

    /**
     * The number of operations that don't reference this input object field (the field is missing or undefined).
     *
     * Generated from protobuf field <code>uint64 missing = 3 [json_name = "missing"];</code>
     *
     * @param  int|string  $var
     *
     * @return $this
     */
    public function setMissing($var)
    {
        GPBUtil::checkUint64($var);
        $this->missing = $var;

        return $this;
    }
}
