<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/Tracing/FederatedTracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\FederatedTracing\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * As FieldStat only gets returned for FTV1 payloads this is a separate message that can be used to collect stats in the router or gateway obtained directly from the request schema and response.
 *
 * Generated from protobuf message <code>LocalFieldStat</code>
 */
class LocalFieldStat extends \Google\Protobuf\Internal\Message
{
    /**
     * required; eg "String!" for User.email:String!
     *
     * Generated from protobuf field <code>string return_type = 1 [json_name = "returnType"];</code>
     */
    protected $return_type = '';
    /**
     * Histogram of returned array sizes
     *
     * Generated from protobuf field <code>repeated sint64 array_size = 2 [json_name = "arraySize"];</code>
     */
    private $array_size;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $return_type
     *           required; eg "String!" for User.email:String!
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $array_size
     *           Histogram of returned array sizes
     * }
     */
    public function __construct($data = NULL) {
        \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /**
     * required; eg "String!" for User.email:String!
     *
     * Generated from protobuf field <code>string return_type = 1 [json_name = "returnType"];</code>
     * @return string
     */
    public function getReturnType()
    {
        return $this->return_type;
    }

    /**
     * required; eg "String!" for User.email:String!
     *
     * Generated from protobuf field <code>string return_type = 1 [json_name = "returnType"];</code>
     * @param string $var
     * @return $this
     */
    public function setReturnType($var)
    {
        GPBUtil::checkString($var, True);
        $this->return_type = $var;

        return $this;
    }

    /**
     * Histogram of returned array sizes
     *
     * Generated from protobuf field <code>repeated sint64 array_size = 2 [json_name = "arraySize"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArraySize()
    {
        return $this->array_size;
    }

    /**
     * Histogram of returned array sizes
     *
     * Generated from protobuf field <code>repeated sint64 array_size = 2 [json_name = "arraySize"];</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArraySize($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::SINT64);
        $this->array_size = $arr;

        return $this;
    }

}

