<?php declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/Tracing/FederatedTracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\FederatedTracing\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PathErrorStats</code>.
 */
class PathErrorStats extends \Google\Protobuf\Internal\Message
{
    /** Generated from protobuf field <code>map<string, .PathErrorStats> children = 1 [json_name = "children"];</code> */
    private $children;

    /** Generated from protobuf field <code>uint64 errors_count = 4 [json_name = "errorsCount"];</code> */
    protected $errors_count = 0;

    /** Generated from protobuf field <code>uint64 requests_with_errors_count = 5 [json_name = "requestsWithErrorsCount"];</code> */
    protected $requests_with_errors_count = 0;

    /**
     * Constructor.
     *
     * @param  array  $data {
     *     Optional. Data for populating the Message object.
     *
     *     @var array|\Google\Protobuf\Internal\MapField $children
     *     @var int|string $errors_count
     *     @var int|string $requests_with_errors_count
     * }
     */
    public function __construct($data = null)
    {
        Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .PathErrorStats> children = 1 [json_name = "children"];</code>.
     *
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * Generated from protobuf field <code>map<string, .PathErrorStats> children = 1 [json_name = "children"];</code>.
     *
     * @param  array|\Google\Protobuf\Internal\MapField  $var
     *
     * @return $this
     */
    public function setChildren($var)
    {
        $arr = GPBUtil::checkMapField($var, GPBType::STRING, GPBType::MESSAGE, PathErrorStats::class);
        $this->children = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 errors_count = 4 [json_name = "errorsCount"];</code>.
     *
     * @return int|string
     */
    public function getErrorsCount()
    {
        return $this->errors_count;
    }

    /**
     * Generated from protobuf field <code>uint64 errors_count = 4 [json_name = "errorsCount"];</code>.
     *
     * @param  int|string  $var
     *
     * @return $this
     */
    public function setErrorsCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->errors_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 requests_with_errors_count = 5 [json_name = "requestsWithErrorsCount"];</code>.
     *
     * @return int|string
     */
    public function getRequestsWithErrorsCount()
    {
        return $this->requests_with_errors_count;
    }

    /**
     * Generated from protobuf field <code>uint64 requests_with_errors_count = 5 [json_name = "requestsWithErrorsCount"];</code>.
     *
     * @param  int|string  $var
     *
     * @return $this
     */
    public function setRequestsWithErrorsCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->requests_with_errors_count = $var;

        return $this;
    }
}
