<?php declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/Tracing/FederatedTracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\FederatedTracing\Proto;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PathErrorStats</code>.
 */
class PathErrorStats extends \Google\Protobuf\Internal\Message
{
    /** Generated from protobuf field <code>map<string, .PathErrorStats> children = 1;</code> */
    private $children;

    /** Generated from protobuf field <code>uint64 errors_count = 4;</code> */
    protected $errors_count = 0;

    /** Generated from protobuf field <code>uint64 requests_with_errors_count = 5;</code> */
    protected $requests_with_errors_count = 0;

    /**
     * Constructor.
     *
     * @param  array  $data {
     *     Optional. Data for populating the Message object.
     *
     *     @var array|\Google\Protobuf\Internal\MapField $children
     *     @var int|string $errors_count
     *     @var int|string $requests_with_errors_count
     * }
     */
    public function __construct($data = null)
    {
        \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .PathErrorStats> children = 1;</code>.
     *
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * Generated from protobuf field <code>map<string, .PathErrorStats> children = 1;</code>.
     *
     * @return $this
     */
    public function setChildren(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\PathErrorStats::class);
        $this->children = $arr;

        return $this;
    }

    /** Generated from protobuf field <code>uint64 errors_count = 4;</code> */
    public function getErrorsCount(): int|string
    {
        return $this->errors_count;
    }

    /**
     * Generated from protobuf field <code>uint64 errors_count = 4;</code>.
     *
     * @return $this
     */
    public function setErrorsCount(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->errors_count = $var;

        return $this;
    }

    /** Generated from protobuf field <code>uint64 requests_with_errors_count = 5;</code> */
    public function getRequestsWithErrorsCount(): int|string
    {
        return $this->requests_with_errors_count;
    }

    /**
     * Generated from protobuf field <code>uint64 requests_with_errors_count = 5;</code>.
     *
     * @return $this
     */
    public function setRequestsWithErrorsCount(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->requests_with_errors_count = $var;

        return $this;
    }
}
