<?php declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/Tracing/FederatedTracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\FederatedTracing\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A sequence of traces and stats. If Report.traces_pre_aggregated (at the top
 * level of the report) is false, an individual operation should either be
 * described as a trace or as part of stats, but not both. If that flag
 * is true, then all operations are described as stats and some are also
 * described as traces.
 *
 * Generated from protobuf message <code>TracesAndStats</code>
 */
class TracesAndStats extends \Google\Protobuf\Internal\Message
{
    /** Generated from protobuf field <code>repeated .Trace trace = 1 [json_name = "trace"];</code> */
    private $trace;

    /** Generated from protobuf field <code>repeated .ContextualizedStats stats_with_context = 2 [json_name = "statsWithContext"];</code> */
    private $stats_with_context;

    /**
     * This describes the fields referenced in the operation. Note that this may
     * include fields that don't show up in FieldStats (due to being interface fields,
     * being nested under null fields or empty lists or non-matching fragments or
     * `&#64;include` or `&#64;skip`, etc). It also may be missing fields that show up in FieldStats
     * (as FieldStats will include the concrete object type for fields referenced
     * via an interface type).
     *
     * Generated from protobuf field <code>map<string, .ReferencedFieldsForType> referenced_fields_by_type = 4 [json_name = "referencedFieldsByType"];</code>
     */
    private $referenced_fields_by_type;

    /**
     * This field is used to validate that the algorithm used to construct `stats_with_context`
     * matches similar algorithms in Apollo's servers. It is otherwise ignored and should not
     * be included in reports.
     *
     * Generated from protobuf field <code>repeated .Trace internal_traces_contributing_to_stats = 3 [json_name = "internalTracesContributingToStats"];</code>
     */
    private $internal_traces_contributing_to_stats;

    /**
     * This is an optional field that is used to provide more context to the key of this object within the
     * traces_per_query map. If it's omitted, we assume the key is a standard operation name and signature key.
     *
     * Generated from protobuf field <code>.QueryMetadata query_metadata = 5 [json_name = "queryMetadata"];</code>
     */
    protected $query_metadata;

    /**
     * Constructor.
     *
     * @param  array  $data {
     *     Optional. Data for populating the Message object.
     *
     *     @var array<\Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Trace>|\Google\Protobuf\Internal\RepeatedField $trace
     *     @var array<\Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\ContextualizedStats>|\Google\Protobuf\Internal\RepeatedField $stats_with_context
     *     @var array|\Google\Protobuf\Internal\MapField $referenced_fields_by_type
     *           This describes the fields referenced in the operation. Note that this may
     *           include fields that don't show up in FieldStats (due to being interface fields,
     *           being nested under null fields or empty lists or non-matching fragments or
     *           `&#64;include` or `&#64;skip`, etc). It also may be missing fields that show up in FieldStats
     *           (as FieldStats will include the concrete object type for fields referenced
     *           via an interface type).
     *     @var array<\Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Trace>|\Google\Protobuf\Internal\RepeatedField $internal_traces_contributing_to_stats
     *           This field is used to validate that the algorithm used to construct `stats_with_context`
     *           matches similar algorithms in Apollo's servers. It is otherwise ignored and should not
     *           be included in reports.
     *     @var \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\QueryMetadata $query_metadata
     *           This is an optional field that is used to provide more context to the key of this object within the
     *           traces_per_query map. If it's omitted, we assume the key is a standard operation name and signature key.
     * }
     */
    public function __construct($data = null)
    {
        Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Trace trace = 1 [json_name = "trace"];</code>.
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTrace()
    {
        return $this->trace;
    }

    /**
     * Generated from protobuf field <code>repeated .Trace trace = 1 [json_name = "trace"];</code>.
     *
     * @param  array<\Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Trace>|\Google\Protobuf\Internal\RepeatedField  $var
     *
     * @return $this
     */
    public function setTrace($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Trace::class);
        $this->trace = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ContextualizedStats stats_with_context = 2 [json_name = "statsWithContext"];</code>.
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStatsWithContext()
    {
        return $this->stats_with_context;
    }

    /**
     * Generated from protobuf field <code>repeated .ContextualizedStats stats_with_context = 2 [json_name = "statsWithContext"];</code>.
     *
     * @param  array<\Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\ContextualizedStats>|\Google\Protobuf\Internal\RepeatedField  $var
     *
     * @return $this
     */
    public function setStatsWithContext($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, ContextualizedStats::class);
        $this->stats_with_context = $arr;

        return $this;
    }

    /**
     * This describes the fields referenced in the operation. Note that this may
     * include fields that don't show up in FieldStats (due to being interface fields,
     * being nested under null fields or empty lists or non-matching fragments or
     * `&#64;include` or `&#64;skip`, etc). It also may be missing fields that show up in FieldStats
     * (as FieldStats will include the concrete object type for fields referenced
     * via an interface type).
     *
     * Generated from protobuf field <code>map<string, .ReferencedFieldsForType> referenced_fields_by_type = 4 [json_name = "referencedFieldsByType"];</code>
     *
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getReferencedFieldsByType()
    {
        return $this->referenced_fields_by_type;
    }

    /**
     * This describes the fields referenced in the operation. Note that this may
     * include fields that don't show up in FieldStats (due to being interface fields,
     * being nested under null fields or empty lists or non-matching fragments or
     * `&#64;include` or `&#64;skip`, etc). It also may be missing fields that show up in FieldStats
     * (as FieldStats will include the concrete object type for fields referenced
     * via an interface type).
     *
     * Generated from protobuf field <code>map<string, .ReferencedFieldsForType> referenced_fields_by_type = 4 [json_name = "referencedFieldsByType"];</code>
     *
     * @param  array|\Google\Protobuf\Internal\MapField  $var
     *
     * @return $this
     */
    public function setReferencedFieldsByType($var)
    {
        $arr = GPBUtil::checkMapField($var, GPBType::STRING, GPBType::MESSAGE, ReferencedFieldsForType::class);
        $this->referenced_fields_by_type = $arr;

        return $this;
    }

    /**
     * This field is used to validate that the algorithm used to construct `stats_with_context`
     * matches similar algorithms in Apollo's servers. It is otherwise ignored and should not
     * be included in reports.
     *
     * Generated from protobuf field <code>repeated .Trace internal_traces_contributing_to_stats = 3 [json_name = "internalTracesContributingToStats"];</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInternalTracesContributingToStats()
    {
        return $this->internal_traces_contributing_to_stats;
    }

    /**
     * This field is used to validate that the algorithm used to construct `stats_with_context`
     * matches similar algorithms in Apollo's servers. It is otherwise ignored and should not
     * be included in reports.
     *
     * Generated from protobuf field <code>repeated .Trace internal_traces_contributing_to_stats = 3 [json_name = "internalTracesContributingToStats"];</code>
     *
     * @param  array<\Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Trace>|\Google\Protobuf\Internal\RepeatedField  $var
     *
     * @return $this
     */
    public function setInternalTracesContributingToStats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Trace::class);
        $this->internal_traces_contributing_to_stats = $arr;

        return $this;
    }

    /**
     * This is an optional field that is used to provide more context to the key of this object within the
     * traces_per_query map. If it's omitted, we assume the key is a standard operation name and signature key.
     *
     * Generated from protobuf field <code>.QueryMetadata query_metadata = 5 [json_name = "queryMetadata"];</code>
     *
     * @return \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\QueryMetadata|null
     */
    public function getQueryMetadata()
    {
        return $this->query_metadata;
    }

    public function hasQueryMetadata()
    {
        return isset($this->query_metadata);
    }

    public function clearQueryMetadata()
    {
        unset($this->query_metadata);
    }

    /**
     * This is an optional field that is used to provide more context to the key of this object within the
     * traces_per_query map. If it's omitted, we assume the key is a standard operation name and signature key.
     *
     * Generated from protobuf field <code>.QueryMetadata query_metadata = 5 [json_name = "queryMetadata"];</code>
     *
     * @param  \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\QueryMetadata  $var
     *
     * @return $this
     */
    public function setQueryMetadata($var)
    {
        GPBUtil::checkMessage($var, QueryMetadata::class);
        $this->query_metadata = $var;

        return $this;
    }
}
