<?php declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/Tracing/FederatedTracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\FederatedTracing\Proto;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TypeStat</code>.
 */
class TypeStat extends \Google\Protobuf\Internal\Message
{
    /**
     * Key is (eg) "email" for User.email:String!
     *
     * Generated from protobuf field <code>map<string, .FieldStat> per_field_stat = 3;</code>
     */
    private $per_field_stat;

    /**
     * Constructor.
     *
     * @param  array  $data {
     *     Optional. Data for populating the Message object.
     *
     *     @var array|\Google\Protobuf\Internal\MapField $per_field_stat
     *           Key is (eg) "email" for User.email:String!
     * }
     */
    public function __construct($data = null)
    {
        \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /**
     * Key is (eg) "email" for User.email:String!
     *
     * Generated from protobuf field <code>map<string, .FieldStat> per_field_stat = 3;</code>
     *
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPerFieldStat()
    {
        return $this->per_field_stat;
    }

    /**
     * Key is (eg) "email" for User.email:String!
     *
     * Generated from protobuf field <code>map<string, .FieldStat> per_field_stat = 3;</code>
     *
     * @return $this
     */
    public function setPerFieldStat(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\FieldStat::class);
        $this->per_field_stat = $arr;

        return $this;
    }
}
