<?php declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/Tracing/FederatedTracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Trace\QueryPlanNode;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Trace.QueryPlanNode.DeferredNodeDepends</code>.
 */
class DeferredNodeDepends extends \Google\Protobuf\Internal\Message
{
    /** Generated from protobuf field <code>string id = 1 [json_name = "id"];</code> */
    protected $id = '';

    /** Generated from protobuf field <code>string defer_label = 2 [json_name = "deferLabel"];</code> */
    protected $defer_label = '';

    /**
     * Constructor.
     *
     * @param  array  $data {
     *     Optional. Data for populating the Message object.
     *
     *     @var string $id
     *     @var string $defer_label
     * }
     */
    public function __construct($data = null)
    {
        \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>.
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>.
     *
     * @param  string  $var
     *
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string defer_label = 2 [json_name = "deferLabel"];</code>.
     *
     * @return string
     */
    public function getDeferLabel()
    {
        return $this->defer_label;
    }

    /**
     * Generated from protobuf field <code>string defer_label = 2 [json_name = "deferLabel"];</code>.
     *
     * @param  string  $var
     *
     * @return $this
     */
    public function setDeferLabel($var)
    {
        GPBUtil::checkString($var, true);
        $this->defer_label = $var;

        return $this;
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DeferredNodeDepends::class, \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Trace_QueryPlanNode_DeferredNodeDepends::class);
