<?php declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/Tracing/FederatedTracing/reports.proto

namespace Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Trace\QueryPlanNode;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;

/**
 * This represents a set of nodes to be executed sequentially by the Router/Gateway executor.
 *
 * Generated from protobuf message <code>Trace.QueryPlanNode.SequenceNode</code>
 */
class SequenceNode extends \Google\Protobuf\Internal\Message
{
    /** Generated from protobuf field <code>repeated .Trace.QueryPlanNode nodes = 1 [json_name = "nodes"];</code> */
    private $nodes;

    /**
     * Constructor.
     *
     * @param  array  $data {
     *     Optional. Data for populating the Message object.
     *
     *     @var array<\Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Trace\QueryPlanNode>|\Google\Protobuf\Internal\RepeatedField $nodes
     * }
     */
    public function __construct($data = null)
    {
        \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Metadata\Reports::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Trace.QueryPlanNode nodes = 1 [json_name = "nodes"];</code>.
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNodes()
    {
        return $this->nodes;
    }

    /**
     * Generated from protobuf field <code>repeated .Trace.QueryPlanNode nodes = 1 [json_name = "nodes"];</code>.
     *
     * @param  array<\Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Trace\QueryPlanNode>|\Google\Protobuf\Internal\RepeatedField  $var
     *
     * @return $this
     */
    public function setNodes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Trace\QueryPlanNode::class);
        $this->nodes = $arr;

        return $this;
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SequenceNode::class, \Nuwave\Lighthouse\Tracing\FederatedTracing\Proto\Trace_QueryPlanNode_SequenceNode::class);
