name: "Autoformat"

on:
  push:

jobs:
  composer-normalize:
    name: "composer-normalize"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"
        with:
          ref: "${{ github.head_ref }}"

      - name: "Run composer normalize"
        uses: "docker://ergebnis/composer-normalize-action:0.8.0"

      - name: "Commit fixed composer.json"
        uses: "stefanzweifel/git-auto-commit-action@v4.1.6"
        with:
          commit_message: "Normalize composer.json"
          branch: "${{ github.head_ref }}"

  prettier:
    name: "Prettify docs"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"
        with:
          ref: "${{ github.head_ref }}"

      - name: "Prettify docs"
        uses: "creyD/prettier_action@v2.2"
        with:
          prettier_options: '--write --tab-width=2 docs/**/**/*.md'
          branch: "${{ github.head_ref }}"
          commit_message: "Prettify docs"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
