name: "Autoformat"
on:
  push:

jobs:
  composer-normalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: docker://ergebnis/composer-normalize-action:0.8.0

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Normalize composer.json

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: creyD/prettier_action@v2.2
        with:
          prettier_options: --write --tab-width=2 docs/**/**/*.md
          branch: ${{ github.head_ref }}
          commit_message: Prettify docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
