name: "Build protobuf"
on:
  push:
    branches:
      - '*'
    paths:
      - '**.proto'
      - 'buf.gen.yaml'

jobs:
  proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: bufbuild/buf-setup-action@v1

      - run: |
          buf generate
          rm -rf src/Tracing/FederatedTracing/Proto
          mv proto-tmp/Nuwave/Lighthouse/Tracing/FederatedTracing/Proto src/Tracing/FederatedTracing/Proto
          rm -rf proto-tmp

      - run: git pull

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply proto changes
