name: "Build protobuf"
on:
  push:
    branches:
      - '*'
    paths:
      - '**.proto'
      - 'buf.gen.yaml'

jobs:
  proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: mbstring
          php-version: 8.2

      - run: composer install --no-interaction --no-progress --no-suggest

      - uses: bufbuild/buf-setup-action@v1

      - run: |
          buf generate
          rm -rf src/Tracing/FederatedTracing/Proto
          mv proto-tmp/Nuwave/Lighthouse/Tracing/FederatedTracing/Proto src/Tracing/FederatedTracing/Proto
          rm -rf proto-tmp

      - run: vendor/bin/php-cs-fixer fix src/Tracing/FederatedTracing/Proto

      - run: git pull

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply proto changes
